### ISSUE TITLE
Dogs

### ISSUE THREAD

**Issue by hwayne** [hne3/Dogs#1]
Dogs

**Comment by hne3** [comment]
![dog-03](https://cloud.githubusercontent.com/assets/8660644/11985951/fc28619c-a997-11e5-8e92-2b6885098491.jpg)

**Comment by hwayne** [comment]
![image](https://cloud.githubusercontent.com/assets/2660212/11985983/0828d6a0-a990-11e5-9f81-11edb949f93d.png)

**Comment by hne3** [comment]
https://www.youtube.com/watch?v=mZpa3nOLOa8

**Comment by hwayne** [comment]
https://www.youtube.com/watch?v=X0-Sv6YnxEc

On Wed, Dec 23, 2015 at 4:16 PM, Haley Eisenshtadt <notifications@github.com

**Comment by hne3** [comment]
https://www.youtube.com/watch?v=D-UmfqFjpl0

**Comment by hwayne** [comment]
https://vimeo.com/14567237

On Wed, Dec 23, 2015 at 4:22 PM, Haley Eisenshtadt <notifications@github.com

**Comment by hne3** [comment]
https://www.youtube.com/watch?v=RutxE_l-N50
